/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PowderRouteImport } from './routes/powder'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as BlogCoversRouteImport } from './routes/blog/covers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PowderRoute = PowderRouteImport.update({
  id: '/powder',
  path: '/powder',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCoversRoute = BlogCoversRouteImport.update({
  id: '/blog/covers',
  path: '/blog/covers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/powder': typeof PowderRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/covers': typeof BlogCoversRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/powder': typeof PowderRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/covers': typeof BlogCoversRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/powder': typeof PowderRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/covers': typeof BlogCoversRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/powder' | '/rss.xml' | '/blog/$slug' | '/blog/covers' | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/powder' | '/rss.xml' | '/blog/$slug' | '/blog/covers' | '/blog'
  id:
    | '__root__'
    | '/'
    | '/powder'
    | '/rss.xml'
    | '/blog/$slug'
    | '/blog/covers'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PowderRoute: typeof PowderRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogCoversRoute: typeof BlogCoversRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/powder': {
      id: '/powder'
      path: '/powder'
      fullPath: '/powder'
      preLoaderRoute: typeof PowderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/covers': {
      id: '/blog/covers'
      path: '/blog/covers'
      fullPath: '/blog/covers'
      preLoaderRoute: typeof BlogCoversRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PowderRoute: PowderRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogCoversRoute: BlogCoversRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
